name: Build & deploy to GitHub Pages

on:
  push:
    branches:
    - master

env:
  CECIL_VERSION: '5.41.0'
  CECIL_BASEURL: '/'
  CONFIG: 'cecil.yml'  
  INTL: 'no' # 'yes' if internationalization extensions are required

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: php:7.4-cli-alpine

    steps:
    - name: Install PHP extensions
      if: env.INTL == 'yes'
      run: |
        apk update
        apk add --no-cache gettext-dev icu-dev
        docker-php-ext-install -j$(nproc) gettext
        docker-php-ext-install -j$(nproc) intl

    - name: Checkout source
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Install theme(s)
      run: |
        if [[ -f "composer.json" ]]; then
          curl -sS https://getcomposer.org/installer | php
          php composer.phar install --prefer-dist --no-dev --no-progress --ansi
        fi

    - name: Build site with Cecil
      run: |
        if [[ -z "$CECIL_VERSION" ]]; then
          echo "Downloading Cecil"
          curl -sSOL https://cecil.app/cecil.phar
        else
          echo "Downloading Cecil $CECIL_VERSION"
          curl -sSOL https://cecil.app/download/$CECIL_VERSION/cecil.phar
        fi
        echo "::group::Build"
        if [[ -z "$CONFIG" ]]; then
          php cecil.phar build -vv --ansi
        else
          echo "::debug::config=$CONFIG"
          php cecil.phar build -vv --config=$CONFIG --ansi
        fi
        echo "::endgroup::"

    - name: Upload site to Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: _site
        path: _site
        if-no-files-found: error

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download site from Artifacts
      uses: actions/download-artifact@v2
      with:
        name: _site
        path: _site

    - name: Deploy site to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        email: arnaud@ligny.org
