name: Build & deploy to GitHub Pages

on:
  push:
    branches:
    - master

env:
  INTL: 'no' # 'yes' if internationalization extensions are required

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: php:7.4-alpine

    steps:
    - name: Install PHP extensions
      if: env.INTL == 'yes'
      run: |
        apk update
        apk add --no-cache gettext-dev icu-dev
        docker-php-ext-install -j$(nproc) gettext
        docker-php-ext-install -j$(nproc) intl

    - name: Checkout source
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Build site with Cecil
      uses: Cecilapp/Cecil-Action@v3
      with:
        config: 'cecil.yml'

    - name: Upload site to Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: _site
        path: _site
        if-no-files-found: error

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download site from Artifacts
      uses: actions/download-artifact@v2
      with:
        name: _site
        path: _site

    - name: Deploy site to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        email: arnaud@ligny.org
